services:
  - type: web
    name: miapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn miapp.miapp.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: miapp
          property: connectionString
