services:
  - type: web
    name: miapp
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn miapp.miapp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: miapp.settings
      - key: PYTHON_VERSION
        value: 3.11
